return new OptionListModule({
    functions:[
        {
            "label":"Edit",
            "fn":function(){
                alert(1);
            }
        },
        {
            "label":"Report",
            "fn":function(){
                alert(1);
            }
        },
        {
            "label":"Archive",
            "fn":function(){
                alert(1);
            }
        },
    ]
})